apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cron
spec:
  schedule: "*/1 * * * *"  # runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test
            image: busybox
            args:
              - /bin/sh
              - -c
              - "date; echo 'CronJob executed successfully!'"
          restartPolicy: OnFailure
