apiVersion: v1
kind: Service
metadata:
  name: demo-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: demo-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-postgres
  template:
    metadata:
      labels:
        app: demo-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: demo
        - name: POSTGRES_USER
          value: demo_user
        - name: POSTGRES_PASSWORD
          value: demo_pass
        ports:
        - containerPort: 5432
