name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run tests (H2)
        run: ./mvnw clean verify -Dspring.profiles.active=test

      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/demo-app:latest .

      - name: Login and Push Docker image
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/demo-app:latest

  deploy-to-vm:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      VM_API_TOKEN: ${{ secrets.VM_API_TOKEN }} # optional if your VM can pull using auth token
      VM_IP: ${{ secrets.VM_IP }}
    steps:
      - name: Trigger VM to pull & run Docker image
        run: |
          # This assumes your VM is configured to auto-pull from Docker Hub
          # You can trigger the VM via API, webhook, or a cron job to run:
          # docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          # docker pull $DOCKER_USERNAME/demo-app:latest
          # docker-compose down --remove-orphans
          # docker-compose up -d
          echo "At this point, your VM should pull the Docker image automatically"
