name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      VM_HOST: ${{ secrets.VM_HOST }}
      VM_USER: ${{ secrets.VM_USER }}
      VM_PORT: ${{ secrets.VM_PORT }}
      VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Step 3: Make mvnw executable
      - name: Make mvnw executable
        run: chmod +x mvnw

      # Step 4: Run tests using H2 in-memory database
      - name: Run tests (H2)
        run: ./mvnw clean verify -Dspring.profiles.active=test

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_USERNAME/demo-app:latest .

      # Step 6: Login and push Docker image
      - name: Push Docker image
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/demo-app:latest

      # Step 7: Deploy to VM
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          port: ${{ secrets.VM_PORT }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/demo
            git pull origin main
            ./mvnw clean package -DskipTests
            docker-compose down --remove-orphans
            docker-compose up -d
