name: CI/CD Pipeline (No SSH)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Step 3: Make mvnw executable
      - name: Make mvnw executable
        run: chmod +x mvnw

      # Step 4: Run tests using H2 database
      - name: Run tests (H2)
        run: ./mvnw clean verify -Dspring.profiles.active=test

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/demo-app:latest .

      # Step 6: Login and push Docker image
      - name: Push Docker image
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/demo-app:latest
