name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      VM_HOST: ${{ secrets.VM_HOST }}
      VM_USER: ${{ secrets.VM_USER }}
      VM_PORT: ${{ secrets.VM_PORT }}
      VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run tests using H2
        run: ./mvnw clean verify -Dspring.profiles.active=test

      - name: Show test failures
        if: failure()
        run: |
          echo "==================== SUREFIRE REPORTS ===================="
          find target/surefire-reports -name "*.txt" -exec cat {} \;
          echo "=========================================================="

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_USERNAME/demo-app:latest .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/demo-app:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          port: ${{ secrets.VM_PORT }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/demo
            git pull origin main
            ./mvnw clean package -DskipTests
            docker-compose down --remove-orphans
            docker-compose up -d
